---
- name: Install starship
  homebrew:
    name:
    - starship
    state: latest

- name: Dotfiles
  file:
    src: "{{ ansible_env.PWD }}/dotfiles/{{ item }}"
    path: "~/.{{ item }}"
    state: link
  with_items:
  - vimrc
  - zprofile
  - zshrc
