---
- name: Install Arduino Development Tools
  homebrew_cask:
    name:
      - arduino
    state: present

- name: esp8266 development git repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{ development_dir }}/{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/espressif/esptool/",
        dest: "esptool" }
    - { repo: "https://github.com/esp8266/Arduino",
        dest: "esp8266-arduino" }

- name: Create Arduino Board Manager directory
  file:
    path: "~/Documents/Arduino/hardware/esp8266com/"
    state: directory
    recurse: yes

- name: Install local board manager
  file:
    src: "{{ development_dir }}/esp8266-arduino"
    path: "~/Documents/Arduino/hardware/esp8266com/esp8266"
    state: link
